const constants = {
  SELECT_TABLE: "SELECT_TABLE",
  TOGGLE_TABLE: "TOGGLE_TABLE",
  INCREMENT_MONEY_EARNED: "INCREMENT_MONEY_EARNED",
  ADD_TABLE_ITEM: "ADD_TABLE_ITEM",
  DELETE_TABLE_ITEM: "DELETE_TABLE_ITEM"
};

export default constants;
